### ISSUE TITLE
Tests are failed locally

### ISSUE THREAD

**Issue by ezhlobo** [theKashey/react-focus-lock#1]
Hello,

I do want to use this component but it failed because `PropTypes` object is not available through React anymore. I made a fork and ran tests locally, and almost all of them are failed:

![screen shot 2017-10-31 at 13 05 25](https://user-images.githubusercontent.com/974552/32218538-2fb2dff0-be3c-11e7-82c3-6bc50dd7ed6f.png)

**Comment by theKashey** [comment]
@ezhlobo - what was due tests were not made inside a "real" browser. Just bumped one dependency and not they are green. 
Thanks for a #1 issue! 🚀

**Comment by ezhlobo** [comment]
@theKashey hey, thank you for quick response. Still get two failed tests:

![screen shot 2017-10-31 at 14 39 04](https://user-images.githubusercontent.com/974552/32222182-5409fec6-be49-11e7-8f78-764ef94ceb78.png)

**Comment by theKashey** [comment]
@ezhlobo - hm.. Green for me. Could you provide your system details?

**Comment by ezhlobo** [comment]
@theKashey Mac OS 10.12.6, node 6.9.1, npm 3.10.8. Let me know what information exactly you need. 

Just one note, when I was writing a new test case, I noticed that we used `setTimeout(..., 1)`. When I increased the timeout to 20 everything became green. What do you think?

**Comment by ezhlobo** [comment]
@theKashey I'm going to check it more detailed in 3-5 hours. Sorry if you have more questions.

**Comment by theKashey** [comment]
@ezhlobo - so it is possible. Focus lock internally used setImmediate, which must be "faster" than setTimeout. And a single setTimeout(0) must be "slower" than 10 setImmediate.

What you can do - try to replace single setTimeout with __double__ setTimout or setImmediate.
Double waiting (not doubled in time) might solve any possible issues.

The second approach - is to replace Zero timeout by some meaningful value. 16, for example.

**Comment by theKashey** [comment]
Does #2 fix this issue?

**Comment by ezhlobo** [comment]
@theKashey it looks so. I did not expect that tests are fixed :). But now I don't get any red test case. We can close this issue.
