### ISSUE TITLE
Closed Modals get add to tabindex by virtue of data-focus-guard

### ISSUE THREAD

**Issue by dpouliot** [theKashey/react-focus-lock#100]
I can tab to a hidden `data-focus-guard` that precedes a closed modal.

![image](https://user-images.githubusercontent.com/2699333/76902146-bc6bdc80-6871-11ea-92aa-bc19d228296c.png)

**Comment by theKashey** [comment]
duplicate of #99 ?

**Comment by dpouliot** [comment]
While this scenario is occuring on the same page, #99 happens when the modal is open, this is happening when the modal is closed.

**Comment by dpouliot** [comment]
Quick update... it appears ` <FocusLock noFocusGuards>` fixes this issue and #99 . I'll update/close as soon as I can confirm.

**Comment by theKashey** [comment]
> A closed modal shouldn't add a hidden element to a page's tabindex.
`<div data-focus-lock-disabled="false>` -> it's active.

**Comment by dpouliot** [comment]
Perhaps I'm using your component wrong. Modal returns:
<FocusLock><div... </FocusLock>
Where the modal is sitting in the dom, either in a closed or open state.

**Comment by theKashey** [comment]
What does mean "closed"? `display:none`? To deactivate `FocusLock` you have to add one more prop `disabled`

**Comment by dpouliot** [comment]
I've got this working, so closing the issue.
