### ISSUE TITLE
FocusLock should have cross-frame behavior controllable

### ISSUE THREAD

**Issue by theKashey** [theKashey/react-focus-lock#104]
> https://github.com/reach/reach-ui/issues/536

I am adding new `crossFrame` option, right now defaults to true, as long as this behaviour might introduce a breaking change for someone.

setting crossFrame=true will work "as today". Focus will try to keep focus
setting crossFrame=false will work "as proposed". Iframes would be treated as "pages", and let you move focus outside.
I am not sure which behaviour is actually correct - iframes are usually a part of a page, a part of your product, and the only exemptions are non-production examples like code-sandbox.

**Comment by moodysalem** [comment]
IMO the default should be false, as it's surprising this behavior is even possible in the browser

**Comment by LukashenkoYevhenii** [comment]
I think this crossFrame option must be described in the documentation.
I faced this issue when tried to use https://github.com/vector-im/element-web inside an iframe and when their modal is open all my inputs lose focus on the main page.

**Comment by LukashenkoYevhenii** [comment]
https://github.com/theKashey/react-focus-lock/pull/220
