### ISSUE TITLE
Safari 11 tab wrap-around not working when buttons are the first and last element

### ISSUE THREAD

**Issue by madou** [theKashey/react-focus-lock#11]
See: https://madou.github.io/react-best-modal/?selectedKind=BestModal&selectedStory=inputs
Click show modal button. Tab through.

When tabbing through in Chrome/Firefox it works as expected, in Safari 11 not so much (doesn't go past the buttons).

**Comment by theKashey** [comment]
<img width="612" alt="screen shot 2017-12-30 at 10 38 08 pm" src="https://user-images.githubusercontent.com/582410/34453848-2567dff0-edb2-11e7-94ba-005ef9768ab8.png">
I recon - you have to last checkbox selected 🍏

**Comment by theKashey** [comment]
Ie `dont fight with a browser` == `dont emulate tabs`

**Comment by madou** [comment]
Hmm ok! Will have a play and report back, thanks man :-)

**Comment by theKashey** [comment]
Anyway - I did not update OS. Maybe a new version do have some surprises.
sh"IT" happens.

**Comment by madou** [comment]
Well yeah `option + tab` works as expected. This is fine I guess! Will read up more on how safari handles tabbing by default.

**Comment by theKashey** [comment]
There are only inputs in the example you provided. Can you explain how to repeat the issue?

**Comment by madou** [comment]
https://www.webpackbin.com/bins/-L1eaYGuXRMVHLXdJpWm

1. Open up Safari 11
2. Tab forwards and backwards wrapping around, you can successfully wrap around
3. Click show buttons
4. Tab fowards and backwards, you can't seem to wrap around

What do you think? I'll test real quick without focus lock to see if its the same behaviour

**Comment by theKashey** [comment]
Version 11.0.2 (12604.4.7.1.4) - everything is ok.
Version 10.1.2 (12603.3.8) - everything is ok.

Could you try this example - https://www.webpackbin.com/bins/-L1ekF_Hb26IhCVJ4Wer
Anyway - it is quite easy to debug this issue, I just need your shoes, your bike, and your laptop. :terminator:

PS: Without focus lock it shall jump to the navigation bar, and NOT return to this page, but start cycle from the top-first element (ie - webpack-bin chrome)

**Comment by madou** [comment]
Ah without focus lock I actually downloaded the files and ran it locally so the whole page was the example, sorry for the confusion :-)

i get the same behaviour in safari with your example.

**Comment by theKashey** [comment]
I'll reach you after 🎆, and we will figure it out. 🎅 🍻
