### ISSUE TITLE
Can't use in IE11 without polyfill

### ISSUE THREAD

**Issue by aldo-roman** [theKashey/react-focus-lock#111]
The library uses `Array.prototype.find` at some point, which is not implemented in IE11 and thus requires the usage of a polyfill to load. I could not find documentation of such requirement. 

Refactoring the method to avoid this method fixed the issue for us.

https://github.com/theKashey/react-focus-lock/blob/188445c5af23e578c2479be696319864061fd7cd/src/Trap.js#L116

**Comment by theKashey** [comment]
Not closed until the package is not published...

**Comment by just-boris** [comment]
Do you have any plans on the next release? Is there anything that is blocking it?

**Comment by theKashey** [comment]
2.4.1 has been released
