### ISSUE TITLE
Nested focus-lock

### ISSUE THREAD

**Issue by qasimalyas** [theKashey/react-focus-lock#119]
This is more of a question. I have a scenario where i would like to lock the inner html when its shown on screen.

https://codesandbox.io/s/priceless-engelbart-iuwwb?file=/src/App.js

For example focus-lock should be first set on the main navigation list when its open. When sub items are shown (by clicking item 4 or item 5) the nested `ul` should then has the lock and presumably the outer main list `disabled` prop becomes true. 

So far I can only see this working with a nested Focus-lock and switching disabled prop to true or false. Is this a feasible approach or is there an alternative solution for such an example?

**Comment by theKashey** [comment]
✅ you can nest locks inside each other, without any need to "disable" parent lock. Only only lock can be active at one time, and FL tracks "the last one" automatically.
⛔️ you probably don't want or need it. That's a little strange user experience. Please don't "lock" users without real need for it.
