### ISSUE TITLE
Return focus not working

### ISSUE THREAD

**Issue by madou** [theKashey/react-focus-lock#12]
happy new year!

this line gets executed when unmounting: 
https://github.com/theKashey/react-focus-lock/blob/be88bb888202df7c35b8e588203c4d3bf4f2c0ac/src/Lock.js#L29

this line is executed sometime after the unmounting: 
https://github.com/theKashey/react-focus-lock/blob/be88bb888202df7c35b8e588203c4d3bf4f2c0ac/src/Trap.js#L25

which means focus can never (synchronously) be returned to the initial element. (even if `returnFocus` is turned off in focus lock. atm i'm getting around this by a `setTimeout`, but that's not great.

thoughts?

**Comment by theKashey** [comment]
Sounds like a bug.

**Comment by theKashey** [comment]
react-focus-lock@1.6.2
You were absolutely right - by the time I've moved focus back trap was still active, and moves it back.
Just deferring this action solves the problem.

**Comment by madou** [comment]
Nice, thanks!

Can we mention in the readme that if consumers want to implement their own return focus logic that they'll have to do is async as well pls? (will be confusing for them if it's not there)

**Comment by theKashey** [comment]
RRrrrrrr. There must be a better way.
Like a cancel scheduled operation on unmount.

**Comment by theKashey** [comment]
Ok. So it is absolutely ok to `disarm` Trap on componentWillUnmount and call .focus without any delay.
But it will not solve the problem, cos if you are the parent component - first will be called your unmount method, and only next the Lock's one.
Ie by the time you `could` return focus by yourself - trap will be active. The same as it was internally.

So - the only way is to document this feature, as you said.
