### ISSUE TITLE
Without sidecar

### ISSUE THREAD

**Issue by maraisr** [theKashey/react-focus-lock#122]
Can there be a lite version that is barebones, without the need to pull in sidecar.

**Comment by theKashey** [comment]
Tell me more about the use case. I am more interested in the meaning of "without" - the "default" export (https://github.com/theKashey/react-focus-lock/blob/master/src/Combination.js) is not using any sideCar, however it is used inside to maintain the same (async) behavior for the end user.
Is it async behavior you are fighting with?

**Comment by maraisr** [comment]
Its more that its a dependency I don't wish to care about. We have byte restrictions, and pulling in sidecar is a just an extra thing. The way we use this lib, we'd never code-split the UI from the logic because they'll both happen at the same time. 

So its more about introducing `/lite` and giving us just the logic with a small UI wrapper perhaps?

**Comment by theKashey** [comment]
Got it. But it will have a while to make necessary adjustments. These days I am starting refactoring like this moving to TypeScript (underlaying focus-lock moved yesterday)

Meanwhile, I would propose you to double-check how much space side-car consumes. It would be not too much.

If you really are byte-restricted - you might use bare `focus-lock` - this library is just a big fat wrapper around it, handling many edge cases you might never need.

[These 10 lines of code](https://github.com/theKashey/react-focus-lock/blob/master/src/Trap.js#L90-L104) are all you really need - you can check with vue-focus-lock or dom-focus-lock.

The rest are "edge cases"

**Comment by theKashey** [comment]
How did you solve the problem?
