### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by jamesplease** [theKashey/react-focus-lock#127]
Hi @theKashey ! Love this library. You may already know this, but React 17 was released a few weeks ago. For the most part it's backwards compatible, so there's a good chance that this lib can just update its peerDep range without any issues. But I'm not certain of that.

I'm just opening this issue to act as a place to track React 17 support for this lib, since I noticed that one didn't already exist (or I missed it!).

**Comment by theKashey** [comment]
Something I want to do every single day, and...

**Comment by wojtekmaj** [comment]
Fixed in e32e7932043551c3339d2ad5e0a08a925e67f780
