### ISSUE TITLE
Compatibility with `focus-lock` 0.8.0

### ISSUE THREAD

**Issue by clark-pan-canva** [theKashey/react-focus-lock#128]
I'm trying to use `react-focus-lock` with `focus-lock@0.8.0`.

Semver says it should be compatible, but I get this error when I force `react-focus-lock` to use `focus-lock@0.8.0`:

<img width="888" alt="Screen Shot 2020-11-16 at 2 16 10 pm" src="https://user-images.githubusercontent.com/64457019/99209047-52e40980-2816-11eb-933e-726a729e817d.png">

The error comes up from a fresh install of the create-react-app project.

**Comment by theKashey** [comment]
😨 , that entrypoint got lost during migration to typescript.
`focus-lock@0.8.1` was relesed, give it a few minutes and try again. You might need to tweak `yarn.lock` or `package-lock` a little to get a fresh version of a sub dependency.

**Comment by clark-pan-canva** [comment]
That fixes it.

Love the fast response btw! You have my thanks.
