### ISSUE TITLE
Focus guards causing page behind to scroll to the bottom when tabbing through

### ISSUE THREAD

**Issue by madou** [theKashey/react-focus-lock#13]
To replicate:

1. Visit
https://madou.github.io/react-best-modal/?selectedKind=Styling&selectedStory=and%20finally%20also%20disabling%20body%20from%20scrolling%20behind&full=0&addons=1&stories=1&panelRight=0

1. Click show modal
1. Tab once
1. See the background behind has scrolled to the bottom

This doesn't happen when I turn on `noFocusGuards` prop (however that then lets us focus to the nav bar - not great)

I'll make up a standalone example without best modal soon! 👍

**Comment by madou** [comment]
Here you go: https://www.webpackbin.com/bins/-L1utkPvAgaAYfSgbt7t

Granted the odd behaviour also only happens with react portals, so... 🤷‍♂️

**Comment by theKashey** [comment]
Ok. Will try to fix.

**Comment by theKashey** [comment]
Sorry, @madou, I failed to fix it.
Actually Trap does contain code about `scroll preventing` but is works only for Safari :(
Actually - focus guards were designed to work out this problem.
Just move FocusLock inside div, and jump will disappear, as long guards will be `close` to the rest of tabbable components.
```js
 <div style={{ top: 0, position: 'fixed', backgroundColor: 'red', height: 500, width: 500 }}>
    <FocusLock>
    <input />
    i am modal
    <input />
     </FocusLock> 
  </div>
```
https://www.webpackbin.com/bins/-L1vUgmz1_vbliSKfK0_

**Comment by madou** [comment]
Hmm okay will give it a shot - thanks :)

**Comment by madou** [comment]
btw atm you're typing focuslock children as `children: React.ReactElement<any>`. is that correct? (only one child allowed?) or would `React.ReactNode` work?

**Comment by theKashey** [comment]
Sure. What's the correct type for PropTypes.node?

**Comment by madou** [comment]
```
import * as React from 'react';

interface Props {
  children: React.ReactNode;
}
```

thanks :-)

**Comment by theKashey** [comment]
@madou  - react-focus-lock@1.6.3

**Comment by madou** [comment]
awesome! thanks so much

might be a good troubleshooting thing to mention too in the readme about all this
