### ISSUE TITLE
[Question] it doesn't focus on the first element 

### ISSUE THREAD

**Issue by Whooolia** [theKashey/react-focus-lock#135]
Hi just want to understand the behaviour

when the modal opened, it doesn't focus on the first element, instead the second.

I tried to add `data-autofocus` on the first element but it didn't work.

Is there any reason that it focuses on the second one instead? or anyone can help me how to focus on the first element?

![Screenshot 2021-01-18 at 15 27 14](https://user-images.githubusercontent.com/36998110/104879673-a81cd280-59a1-11eb-852c-c085bb7e89dc.png)

**Comment by theKashey** [comment]
It's not possible to answer this question without seeing an example or at least a code snipet.
- are you able to `tab` (shift+tab in this case) to the first element
- what would happen if you place Calendar in another place?
- what else is not working?

**Comment by episode17** [comment]
I was just struggling with this, for me it was a "focus-visible" thing. The first element would be selected but it would only show the focus styles when I tabbed to the 2nd.
