### ISSUE TITLE
[Bug] FocusLock causes transition not to trigger the first time

### ISSUE THREAD

**Issue by emadabdulrahim** [theKashey/react-focus-lock#146]
### What packages are being used?

@headlessui/react v1.1.0
react-focus-lock  v2.5.0

### What browser are you using?

Chrome

### Reproduction repository

https://codesandbox.io/s/winter-grass-gk2t1?file=/src/App.js

### Describe your issue

I'm having trouble getting the transition to work on the first time the state changes. I'm using `react-focus-lock` to bring focus inside when a component mounts and keep focus locked inside (My real example is SideSheet and Dialog components). You'll notice it works fine afterwards. 

If I remove `FocusLock` component it works fine, but I've been trying to figure out why it messes up the transition only on the first mount. Any help would be greatly appreciated 🙏🏽

**Comment by theKashey** [comment]
Sounds like it's related to the sidecar functionality - it's the only one which might work differently across renders. But honestly - I have no idea :)

**Comment by theKashey** [comment]
It can work the other way around - https://codesandbox.io/s/quirky-currying-5d5gh?file=/src/App.js
