### ISSUE TITLE
Slow performance in JSDOM

### ISSUE THREAD

**Issue by just-boris** [theKashey/react-focus-lock#151]
This simple component takes 200ms to render in JSDOM environment on my laptop:

```js
function Demo() {
  return (
    <FocusLock>
      <button>Test</button>
      <button>Test</button>
      <button>Test</button>
    </FocusLock>
  );
}
```

I investigated why this is happening, found the bottleneck in [isElementHidden function](https://github.com/theKashey/focus-lock/blob/a65b9aef7a8d89b0a7787e97b4cdbc6c7981d70d/src/utils/is.ts#L1-L8). It calls `window.computedStyle` for each node and all their parents, but this is an expensive operation in JSDOM (~5ms for me). The more nodes in DOM, the slower it becomes. 

Here you can also find the demo to reproduce with the same dependencies (latest create-react-app): https://github.com/just-boris/thousand-cuts

**Comment by theKashey** [comment]
> related -  #125

I could not skip this check, but I can quite easily memoize calls to the common parents which should greatly reduce the complexity of this operation.

Technically speaking there are better ways to resolve the problem - for example, make this operation _lazy_, and call only when needed, and it's needed only for the first or the last element, but...

Let's start from a small step.
