### ISSUE TITLE
[feature request] `preventScroll` Option on Focus Override

### ISSUE THREAD

**Issue by danlevy1** [theKashey/react-focus-lock#162]
# Description of Feature
Currently, `react-focus-lock` allows you to pass in focus options (including `preventScroll: true`) to the `returnFocus` prop (see https://github.com/theKashey/react-focus-lock/pull/84 and https://github.com/theKashey/focus-lock/pull/23). I am looking for a prop to add focus options to the logic that brings focus back to the focus lock when a focus event occurs outside of the focus lock.

# Use-Case
I am creating a `Popover` component that uses `react-focus-lock` that opens when an anchor/reference button is clicked. When the `Popover` is open, the user is able to scroll around the page. If the user scrolls to the point where the `Popover` is out of view and then clicks on a `button` _outside_ of the `Popover`, some browsers (including Chrome) scroll back to the open `Popover`. The reason is that some browsers focus a `button` on `mousedown`, which I'm assuming causes the focus lock inside of the `Popover` to grab focus again. I would like to disable scrolling when this `Popover` focus event occurs using `preventScroll: true`.

# Example
Here is a small example of the scroll behavior: https://codesandbox.io/s/react-focus-lock-prevent-scroll-1hjn3?file=/src/App.js

To reproduce:
1. Make sure the focus lock is enabled (see button at the top)
2. Scroll down to the bottom of the page
3. Click and hold on the button called "Button outside of focus lock" to trigger the `mousedown` event.
4. Chrome will scroll back to the top of the page where the focus lock is. I want to be able to prevent this part of the reproduction.

**Comment by theKashey** [comment]
A very sound addition very simple to implement. Thank you for providing a good use case, it's really not the best user experience so easy to improve.

**Comment by abhimanyu-singh-uber** [comment]
Hi @theKashey, It would be really helpful if we can fix this.
I took a jab at it and have raised a PR in `focus-lock` repo where focus is being done. Please have a look at it if you get a chance.

Thank you.

PR link- https://github.com/theKashey/focus-lock/pull/29

**Comment by theKashey** [comment]
@abhimanyu-singh-uber - thank you for the implementation. I'll handle the rest

**Comment by abhimanyu-singh-uber** [comment]
Thank you @theKashey

**Comment by walliby** [comment]
Wow I just ran into the exact same problem with the exact same use case. Thanks so much for addressing this!

**Comment by theKashey** [comment]
`2.7.0` has been release. A new prop - `focusOptions` has been added.

**Comment by abhimanyu-singh-uber** [comment]
@theKashey We would need to merge this [PR](https://github.com/theKashey/react-focus-lock/pull/186) & release react-focus-lock again for the changes to get in.

The react-focus-lock is taking in the previous version of focus-lock.
