### ISSUE TITLE
How can I add some elements outside the focus-lock component to the exception?

### ISSUE THREAD

**Issue by Abdubek** [theKashey/react-focus-lock#165]
I need to add hotkey for elements in the header, some dropdown components, and I need to focus on hotkey

**Comment by Abdubek** [comment]
I've tried adding header elements to shards, but I do not like this behavior, I would like to enable focusing of the element in the header only with hot key, and after select kill the ability to focus using the tab

**Comment by theKashey** [comment]
I should have documented this better but there are two ways to handle this:
- whitelist prop on FocusLock
- data argument on the target - refer to this section https://github.com/theKashey/focus-lock/blob/125a50bc53fdc2cbb7705327790ecff4f3289ba1/README.md#focus-fighting

**Comment by Abdubek** [comment]
great, i solved it with data-no-focus-lock, it works very cool
