### ISSUE TITLE
Autofocus not working correctly

### ISSUE THREAD

**Issue by Vanals** [theKashey/react-focus-lock#168]
Hi 

We are using "react-focus-lock": "^2.5.0" and when we try to use the autofocus feature it does not seems to work properly.
Below is just part of the code, to show you the key parts, react-focus-lock, and where we are passing the data-autofocus attribute.

```
    <>
      {renderOverlay(handleOverlayClick)}
      <FocusLock
        disabled={!open}
        onActivation={handleOnLockActivation}
        onDeactivation={handleOnLockDeactivation}
      >
        {children && children(handleCloseButtonClick)}
      </FocusLock>
    </>
```

then setting the autofocus property inside one of the element

`<Button data-autofocus>Ok</Button>`

I even tried the following but did not work.
```
 <AutoFocusInside>
   <Button onClick={() => {console.log('okok')}}>Ok</Button>
</AutoFocusInside>   
```

Once I open the dialog, the `Ok` button **does not** have any focus. The focus is given **only** after I press the tab.

What I would expect is the autofocus to be given immediately on open; also for conforming to Accessibility guidelines, without the need to press tab first.

Thank you!

**Comment by Vanals** [comment]
Was related to our code !

**Comment by theKashey** [comment]
In any case, you have managed to solve this problem faster than me 🐌 

Sorry, was going to answer yesterday, asking for a reproducible example, as this functionality is covered by tests, and postponed sending the comment to find that test...
