### ISSUE TITLE
originalFocusedElement cannot be garbage collected when returnFocus is false

### ISSUE THREAD

**Issue by mariuslukose** [theKashey/react-focus-lock#173]
**Description**

- _onActivation_ handler in _Lock.js_ file sets _originalFocusedElement_ ref to _document.activeElement_ (if it exists): https://github.com/theKashey/react-focus-lock/blob/6117039973dbceb2af79f31ba74c2dedcf065a10/src/Lock.js#L46
- But it does not get reset in _returnFocus_ handler if _returnFocus_ prop isn't true (nor, apparently, anywhere else..): https://github.com/theKashey/react-focus-lock/blob/6117039973dbceb2af79f31ba74c2dedcf065a10/src/Lock.js#L64

**Issue**
If _originalFocusedElement_ is removed from DOM, but _Lock_ component is not, then that _originalFocusedElement_ cannot be garbage collected causing a memory leak.

Maybe _originalFocusedElement_ ref could be reset in _returnFocus_ handler, even when _returnFocus_ prop is false?

**Comment by theKashey** [comment]
Good catch. Let me refactor the code a little bit to make `onDeactivation` act as a proper destructor.
