### ISSUE TITLE
Method to not lock mouseEvent focusing

### ISSUE THREAD

**Issue by tounsoo** [theKashey/react-focus-lock#176]
We have a use case where we want to focusLock on tabs but not on mouse click.

Here is an example where we try to make that happen but the problem we are facing is that it will require 2 clicks to focus on the outside input. Any idea on how to make this happen without requiring 2 clicks?

https://codesandbox.io/s/hardcore-gagarin-mjh4v?file=/index.js

**Comment by tounsoo** [comment]
@theKashey Thank you! I used the second option and created onClickOutside useEffect to handle it :D

**Comment by tounsoo** [comment]
You can checkout the codesandbox, I updated it and made it into a FC so I can reuse it

**Comment by theKashey** [comment]
Amazing! Thank you @alexreardon for running into this issue, and helping @tounsoo to resolve theirs.
