### ISSUE TITLE
Does not use ownerDocument (doesn't work in new windows)

### ISSUE THREAD

**Issue by LoganDark** [theKashey/react-focus-lock#183]
I am searching for another library to solve [this issue](https://github.com/tailwindlabs/headlessui/issues/966), but this library seems to have the exact same issue. This means I can't use it, but I would like to open this issue anyway so that maybe this functionality could be added.

**Comment by theKashey** [comment]
Got you. There is just a few places where we access document (usually document.activeElement) and it might be not the right owner of a current element managed by focus-lock.

In this terms this issue has a very direct connection with #188

**Comment by LoganDark** [comment]
Stale is the most useless possible bot. this issue still exists, not sure how I missed the stale bot being stupid, but this shouldn't have been closed.
