### ISSUE TITLE
returnFocus only works in some versions when using autoFocus to set initial focus

### ISSUE THREAD

**Issue by mikekiska** [theKashey/react-focus-lock#193]
When using `autoFocus` to focus an element within a `<FocusLock returnFocus>...</FocusLock>` focus is only returned using certain versions of react-focus-lock. Examples:
- [2.5.2 - This is the latest version that will return focus when using `autoFocus`](https://codesandbox.io/s/jolly-ride-bcc6q)
- [2.7.1 - Focus is not returned in this version when using `autoFocus`](https://codesandbox.io/s/upbeat-mccarthy-2y63x)
- [2.7.1 - Without `autoFocus` focus is returned in this version](https://codesandbox.io/s/reverent-zeh-2phjq)

Steps to reproduce with first 2.7.1 example above:
1. Click "show modal"
2. Click "close modal 1"
3. Focus should have been returned to the "show modal" button. The button will be red if it has focus.

A second test with 2 modals:
1. Click "show modal"
2. Click "show modal 2"
3. Click "close modal 2"
4. Focus should have been returned to the "show modal 2" button. The button will be red if it has focus.

A third test with 2 modals:
1. Click "show modal"
2. Click "show modal 2"
3. Click "close all modals"
4. Focus should have been returned to the "show modal" button. The button will be red if it has focus.

This may be related to these issues:
- [#126 Multiple modals](https://github.com/theKashey/react-focus-lock/issues/126)
- [#68 Multiple modals and returnFocus](https://github.com/theKashey/react-focus-lock/issues/68)

**Comment by theKashey** [comment]
Just to confirm - this logic became a little complicated. One of the reasons why `returnFocus` [also accepts a function](https://github.com/theKashey/react-focus-lock/blob/master/src/Lock.js#L75) - to handle focus/return/autofocus race conditions.

Probably it's time to really review how this moment works.
