### ISSUE TITLE
Can we have a dialog example in the docs?

### ISSUE THREAD

**Issue by christopher-francisco** [theKashey/react-focus-lock#195]
I'm trying to sort out whether the author intetion is for the component to be used like this:

```tsx
<FocusLock>
  <ModalRoot  // styled-component
    aria-labelledby={ariaLabelledBy}
    aria-modal="true"
    aria-expanded="true"
    role="dialog"
  >
    {children}
  </ModalRoot>
</FocusLock>
```

or the other way around

```tsx
<ModalRoot  // styled-component
  aria-labelledby={ariaLabelledBy}
  aria-modal="true"
  aria-expanded="true"
  role="dialog"
>
  <FocusLock>
    {children}
  </FocusLock>
</ModalRoot>
```

Or maybe in a completely different way:

```tsx
const ModalRoot = styled(FocusLock)`
  // css 
`
<ModalRoot  // styled-component
  aria-labelledby={ariaLabelledBy}
  aria-modal="true"
  aria-expanded="true"
  role="dialog"
>
  {children}
</ModalRoot>
```

The reason I'm bringing this up is because of the extra HTML elements that get added to the DOM around the main one. Not sure if those should be wrabbed by the `[role=dialog]` element or whether it even matters.

I'm more than happy to submit a PR to add the intended usage example to the docs. Just need come clarification. Thanks in advance!

**Comment by theKashey** [comment]
- for just `focus-lock` all variants are valid
- for [focus-on](https://github.com/theKashey/react-focus-on) only the first one is valid, as long as `FocusOn` marks everything except "focused" content as `aria-hidden`, effectively hiding the dialog if it is _outside_ the Lock

Long story short - I would recommend the first variant.
Here is an example passing all requirements for "good modal dialog" - https://codesandbox.io/s/good-react-example-modal-dialog-forked-k4imc?file=/src/App.js

**Comment by christopher-francisco** [comment]
Thank you so much. Would you recommend going for focus-on library instead for a Modal component? Or perhaps it depends, in which case, any resources you could recommend I read in order to make the call?

**Comment by christopher-francisco** [comment]
Thank you so much @theKashey. Would you recommend going for focus-on library instead for a Modal component? Or perhaps it depends, in which case, any resources you could recommend I read in order to make the call?
