### ISSUE TITLE
Disable focus after openning a dialog

### ISSUE THREAD

**Issue by ai** [theKashey/react-focus-lock#20]
How can I disable initial focus on the first focusable element after dialog opening? I need to have no focus after popup open.

I understand that you focus the first element to move focus inside the trap. But if we will focus some element and then we will lose focus on next Tab key press focus will be inside still popup.

I wrote this code in popup wrapper, but it didn’t work:

```js
  componentDidMount () {
      setTimeout(() => {
        document.activeElement.blur()
      }, 100)
  }
```

**Comment by ai** [comment]
@theKashey not sure that I describe it correctly, maybe I describe it better in Telegram :D

**Comment by theKashey** [comment]
This is somehow related to`allowTextSelection` prop (#10). This option just allow __"not"__ to have an active element in the lock.
It does not disable autofocus, but you can blur by your self.

https://codesandbox.io/s/oj01rx089y

**Comment by ai** [comment]
Awesome. Thanks!

**Comment by ai** [comment]
Should we change docs?

**Comment by theKashey** [comment]
Should we change a prop name :)

**Comment by theKashey** [comment]
Even more - should it be a single prop, or two?
 - `shouldHaveFocus`, about allowing not to have a focused element. Maybe disabled by default.
 - `nofocus`(autofocus=false?), about just blurring the active one on lock activation. As long you (usually) have to press some button to open something with a Lock, so the goal is to remove focus from "not Lock", but not had in Lock.

Proper naming always were a problem.

**Comment by ai** [comment]
I like this plan :+1:  especially autobluring :)

**Comment by theKashey** [comment]
Ok, lets flip a coin - `nofocus=true`/`autofocus=false` ?

**Comment by ai** [comment]
`autofocus` is not very clear because it looks like related with `autofocus` attribute.

Maybe `initialFocus: true|false`?

**Comment by theKashey** [comment]
For me `initialFocus` sounds like a focus "target", not the behaviour.

**Comment by ai** [comment]
`focusOnStart`?

**Comment by theKashey** [comment]
`focusOnLock` then, or `noautofocus`, `looseFocus`, `blurred`, `dontFocus`. Meh 💩

**Comment by theKashey** [comment]
They proposed `autoFocus=false` as a best property name.
The bad thing - currently `allowTextSelection` disables that autofocus, and letting you not have a focus inside, doing all the things in a same time, and has to be refactored.

**Comment by theKashey** [comment]
@ai - v1.7.0 just got shipped.
See https://github.com/theKashey/react-focus-lock/releases/tag/1.7.0 for details.
PS: just `<FocusLock autoFocus={false}>....`

**Comment by ai** [comment]
Thanks :) Everything works
