### ISSUE TITLE
FocusLock autoFocus={false} not working when outside component do ref.focus

### ISSUE THREAD

**Issue by Bruceeeeeee** [theKashey/react-focus-lock#204]
In my case we use FocusLock and AutoFocusInside for dialog.
`<AutoFocus>
<AutoFocusInside>
xxx
</AutoFocusInside>
</AutoFocus>`
in some cases like opening dialog by clicking the dropdown menu item, while the dialog is rendering, menu will also do some sth like ref.focus.
In this case, autoFocus={false} not working, it will still focus the first available element.

I tried the disabled props in AutoFocusInside, also not working

**Comment by theKashey** [comment]
- `AutoFocusInside` is _marking_ something inside it as 'focus if there is no other option'. 
  - activated only if focus initially not inside the Lock
- `MoveFocusInside` is a command, moves focus to the first focusable inside it on mount

Can you clarify the desired behavior? You've provided some information about how it is _not working_, but how it _should work_?

**Comment by Bruceeeeeee** [comment]
Hi, I think the desired behavior should be when we set autoFocus=false, it shouldn't focus automatically even the focus is outside the lock. 
To implement this behavior, maybe there could be a 'disabled' props for AutoFocusInside to disable the initial auto focus?

**Comment by theKashey** [comment]
No, this is not how Lock works:
- if focus is outside - it will be moved inside
  - unless the focus is on body, which is "no focus"
- the only way to disable this behavior is to `enabled={false}` and deactivate lock at all.
  - you can listen to `Focus` events inside the Lock and activate it once focus is inside and should be managed.


`autofocus` controls only what will be focused. Without it enabled you are expected to do something `onActivation`, and FocusLock will not interfere.
