### ISSUE TITLE
PropTypes version

### ISSUE THREAD

**Issue by ai** [theKashey/react-focus-lock#21]
Right now we have `prop-types: "15.5.10"` in dependencies. As result, I have 2 PropTypes duplicates in my `node_modules`. Should we replace it to `>=15.5.10`.

**Comment by theKashey** [comment]
Agree.

**Comment by ai** [comment]
But `^15.5.10` will not fix the problem ;). I uses `16.x`.

**Comment by theKashey** [comment]
Ok, my bad. Did not know that I could use `>=`, never used it.
Let me make something for #20 and properly test prop types.
Will be done till your morning.

**Comment by theKashey** [comment]
Maybe it should be >=15.10, but >=15.0

**Comment by theKashey** [comment]
Last version for prop-types is 15.6. Still 15.
