### ISSUE TITLE
content in input can't scroll

### ISSUE THREAD

**Issue by boomler** [theKashey/react-focus-lock#211]
long text in input can't scroll after using focus-lock:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/17810913/158113567-5d46813c-6814-4402-a6bb-01c925017890.png">
Expect can be scrolled horizontally.

**Comment by theKashey** [comment]
Scrolled by what?

**Comment by boomler** [comment]
When using mac, I can use two fingers to scroll text:
https://user-images.githubusercontent.com/17810913/158122632-428cfa02-d497-4de6-b297-ae02a7afce0a.mov

**Comment by theKashey** [comment]
Cannot reproduce the problem using [standard example](https://codesandbox.io/s/5wmrwlvxv4?file=/index.js)
