### ISSUE TITLE
[React 18.0.0] Must explicitly specify the prop children for class and functional components

### ISSUE THREAD

**Issue by dsv-sergey** [theKashey/react-focus-lock#215]
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by theKashey** [comment]
Yep. Update are on the way.

**Comment by theKashey** [comment]
react-focus-lock@2.9.0 should correctly work with React 18. 
But it never was about children, as they always has been explicitly configured.
