### ISSUE TITLE
React 18 support limited by transitive dependency

### ISSUE THREAD

**Issue by billyjanitsch** [theKashey/react-focus-lock#217]
Hi! I see that [2.9.0 was released](https://github.com/theKashey/react-focus-lock/releases/tag/v2.9.0) with the changelog noting React 18 support.

Unfortunately, the library technically isn't compatible with React 18 because it depends on [`react-clientside-effect@^1.2.5`](https://github.com/theKashey/react-clientside-effect), which [doesn't permit React 18 as a peer dep](https://github.com/theKashey/react-clientside-effect/blob/f1a4ead02257b7905659f907186e488018cd2646/package.json#L35). This means that recent versions of npm will refuse to install `react-focus-lock` alongside React 18.

I see that you're also the owner of `react-clientside-effect`, so this should be an easy fix. I've submitted a PR there (https://github.com/theKashey/react-clientside-effect/pull/5) to add React 18 to peer deps. If you merge that and release `react-clientside-effect@1.2.6`, then upgrade the dependency in `react-focus-lock` to `react-clientside-effect@^1.2.6` and release `react-focus-lock@2.9.1`, that will resolve the issue.

Thanks!

**Comment by theKashey** [comment]
https://github.com/theKashey/react-clientside-effect/pull/5 has been released (v1.2.6).
`react-focus-lock` update is waiting for https://github.com/theKashey/focus-lock/issues/36 to be resolved....

**Comment by theKashey** [comment]
Released as `2.9.1`
