### ISSUE TITLE
Set crossFrame as false by default

### ISSUE THREAD

**Issue by yevhenii-username** [theKashey/react-focus-lock#218]
crossFrame the default should be false, as it's surprising this behavior is even possible in the browser. 
You can spend a lot of time trying find issues which related to lost focus on inputs in main windows. 
And after a few days you find that some of dependencies of the project which run inside the iframe use react-focus-lock whithout crossFrame param (just because it's 
non-obvious)

https://github.com/theKashey/react-focus-lock/issues/104#issuecomment-734332075 comment

**Comment by theKashey** [comment]
I cannot change default value of this properly without changing major version as it could be a breaking change.

Instead I would propose the "actual fix" for the problem and make this behavior observable, obvious and no longer surprising.

**Comment by LukashenkoYevhenii** [comment]
But in my case, it not working properly. As you can see, all things inside the iframe (right side) working properly, but if you go to the main window there is  issues with input focus, also all hovers working

https://user-images.githubusercontent.com/17275749/170856751-2d5a72f2-b8d5-4c41-bffb-26fee37f7569.mov
