### ISSUE TITLE
Why is `focusOptions` showing as deprecated?

### ISSUE THREAD

**Issue by jmurzy** [theKashey/react-focus-lock#224]
Being able to pass `preventScroll: true` via focus options is important in cases where auto focus is competing with a transition animation e.g. when sliding in a drawer with [useTransition](https://react-spring.dev/hooks/use-transition#usetransition). Otherwise the potential page shift caused by focus breaks the animation.

https://github.com/theKashey/react-focus-lock/blob/514fc3267a1b8f5dd9f02fdcc89b655ddc39dbef/interfaces.d.ts#L20

**Comment by theKashey** [comment]
The idea is not to _deprecate_ but to prevent accidental usage. Hense _"Use this option only if you known what you are doing"_

**Comment by jmurzy** [comment]
[@deprecated](https://jsdoc.app/tags-deprecated.html) infers it may be removed in a future release. How about we use [@description](https://jsdoc.app/tags-description.html) instead?
