### ISSUE TITLE
Trap loosing focus in case focusable is portaled, within shards, and the last child of the body

### ISSUE THREAD

**Issue by yakunins** [theKashey/react-focus-lock#225]
Steps to reproduce the issue:
1. visit standalone sandbox https://5l92ir.csb.app/
2. press Enable button
3. press Tab several times (and watch trap loosing focus)
4. press Shift+Tab several times (and watch trap doing its job well)

Comments:
1. When running not in standalone sandbox, trap is working: https://codesandbox.io/s/react-focus-lock-forked-5l92ir
2. There is a piece of CSS [in this file](https://codesandbox.io/s/react-focus-lock-forked-5l92ir?file=/index.html), which removes focusable iframe with a link to Codesandbox. If this CSS removed, trap start working.

**Comment by theKashey** [comment]
This is more about feature rather a bug because frankly speaking being able to _leave to the browser interface_ is often correct behavior. 

The expected solution for this is to wrap portalled content with `InFocusGuard`, that _should_ provide the original behavior. But it's not __working__. Even if I have a test for it 🙄

Leave this to me...

**Comment by yakunins** [comment]
Greetings!

> _leave to the browser interface_ is often correct behavior

I am sure in this case the bug is clear: 
1. if **there is a** focusble between trapped-sharded and body boundary, focus is trapped
2. if there is **no focusable** between, focus _leave to the browser interface_

BTW same bug with having shard as first focusable child of the body, revealing on Shift+Tab.

**Comment by yakunins** [comment]
The main problem here is that usually `createPortal` mounts shard as last child of body. 
In my case this is a dropdown of Select, and the Select is within a trap.
Even a dropdown is within shard, it won't work!

**Comment by yakunins** [comment]
> The expected solution for this is to wrap portalled content with `InFocusGuard`, that _should_ provide the original behavior. But it's not **working**. Even if I have a test for it 🙄

Yes. I tried FocusGuard too. They are not working, but might be improved to bugfix in this way:

![image](https://user-images.githubusercontent.com/2505676/184312037-eea5ab72-68dd-4d93-bfce-b3ab7700b8eb.png)

Check this out:
https://8247h3.csb.app/
https://codesandbox.io/s/react-focus-lock-forked-8247h3

**Comment by theKashey** [comment]
So there is a special component with _roving_ tab index over focus guards, which makes them safe and easy to put where needed - https://github.com/theKashey/react-focus-lock/blob/master/src/FocusGuard.js#L18

They are not activating on time 🤷‍♂️
