### ISSUE TITLE
nested FocusLock

### ISSUE THREAD

**Issue by w-green** [theKashey/react-focus-lock#23]
@theKashey could you provide a story for a nested `FocusLock`? I am trying to achieve this with a dialog (modal) that opens another dialog.

When I open the first dialog the focus lock has no autofocus and is not trapped.
When I open the second dialog the focus lock works as expected. 

Here is the code for the dialog component.
```js
<FocusLock>
    <Dialog
        {...props}
    >
        {children}
    </Dialog>
</FocusLock>
```

**Comment by theKashey** [comment]
Maybe your Dialog `portaling` children. FocusLock operates on DOM tree, and any portaled parts of React tree break the stuff (#19).
Try
```js
<Dialog {...props}>
   <FocusLock>
       {children}
   </FocusLock>
</Dialog>
```
