### ISSUE TITLE
[feature] add possibility to pass id to the `FocusLock` element

### ISSUE THREAD

**Issue by grzegorzpokorski** [theKashey/react-focus-lock#237]
It is nice that we can set which html elment should be `FocusLock` by provide a value in `as` prop - I'm very often use that to set `FocusLock` as a `nav` element. I think it would be nice to have a ability to set value for `id` attribute. It is necessary when you would like to set a `aria-*` atributes which needs an  `id`.

**Comment by grzegorzpokorski** [comment]
Oh sorry, I overlooked `lockProps` prop from docs 😬

**Comment by theKashey** [comment]
And probably that was for `react-focus-on`. No worries.
