### ISSUE TITLE
Console warning for react 18 users

### ISSUE THREAD

**Issue by alex-e-leon** [theKashey/react-focus-lock#239]
Hi @theKashey 

When using react-focus-lock with react 18 I get the following error:
`Warning: AutoFocusInside: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

I've opened a pull request here for the issue.
https://github.com/theKashey/react-focus-lock/pull/238

**Comment by theKashey** [comment]
Fix released as a part of 2.9.3
