### ISSUE TITLE
Firefox 59 tabbing gets stopped at anchor tags

### ISSUE THREAD

**Issue by madou** [theKashey/react-focus-lock#24]
hey kash.

see: https://codesandbox.io/s/1w6x7llll in firefox

`tab` through it, you'll see it stops at the anchor tags.
`tab + shift` backwards through it, you'll see it jump to the last anchor, then skip to the "close modal" button, and the continue on.

any ideas why this would happen?

**Comment by theKashey** [comment]
Task 1. disable FocusLock and try to repeat.

As I could see FF does not `tab` on anchors. It just ignores them, (as Safary could do, ie you have to press Option+Tab to tab to "non-input")

How to fix: I've tried all keyboard combination, and I still can't focus on links. Bloody hell! We are dooooomed!

**Comment by theKashey** [comment]
This is OSX behaviour. Could be "fixed" in settings, or overridden in FF configs. But there is nothing I could do.

https://stackoverflow.com/questions/3846868/why-wont-tabindex-work-with-firefox
https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox

**Comment by theKashey** [comment]
<img width="574" alt="screen shot 2018-03-19 at 1 27 10 pm" src="https://user-images.githubusercontent.com/582410/37575089-7101a9fa-2b79-11e8-8114-e7f9f371dfc9.png">

FireFox just follows system settings, and focus-lock follow browser behaviour.

**Comment by theKashey** [comment]
I should point this in readme.

**Comment by ryancalhoun** [comment]
Also, FireFox has to be restarted before the change takes effect.
