### ISSUE TITLE
react-focus-lock with focus-lock@0.11.5 throws when focus taken from cross-origin iframe

### ISSUE THREAD

**Issue by chekrd** [theKashey/react-focus-lock#241]
Hi, go to https://codesandbox.io/s/focus-lock-fail-4gkvyx?file=/src/App.tsx and press Click.

In react-focus-lock@2.9.2 nothing happens, but in @2.9.3 [because of this, I assume,](https://github.com/theKashey/focus-lock/pull/43) it throws and can break the app.

How can I achieve some kind of "try and swallow" approach?

**Comment by theKashey** [comment]
Yep, you cannot and that's a serious regression. Look like I've broken internet one another time 🎉

**Comment by nebrius** [comment]
We ran into this issue too, but pinning `focus-lock` to version `0.11.3` worked around the issue for us. Looking forward to the fix when you get a chance, and thanks for your work!

**Comment by theKashey** [comment]
An update to focus-lock(0.11.6) and react-focus-lock(2.9.4) has been released.

There is still no test securing the right behaviour as JSDOM does not support cross-origin security concerns - https://github.com/jsdom/jsdom/issues/1892

I will add real Browser tests, at least a few, shortly - https://github.com/theKashey/react-focus-lock/issues/242

**Comment by Cesaraugp** [comment]
Hey, can you share a reproduction example for this?
