### ISSUE TITLE
Feature request - Clickaway deactivation

### ISSUE THREAD

**Issue by dimitur2204** [theKashey/react-focus-lock#248]
I am having a problem trying to make the `FocusLock` deactivate once the user clicks away from the locked element. 
Is that possible and if not wouldn't it be nice if there is a prop to enable it?

![no-click-deactivation](https://github.com/theKashey/react-focus-lock/assets/61479393/04a2047b-ac35-4ad8-99f7-9e2f91e5b560)

**Comment by theKashey** [comment]
- Such feature goes agains Single Responsibility Principle and cannot be a part of __focus__ lock
- But __it is__ a part of https://github.com/theKashey/react-focus-on build on top of this library
  - that is the solution you are looking for

**Comment by dimitur2204** [comment]
> * Such feature goes agains Single Responsibility Principle and cannot be a part of **focus** lock
> * But **it is** a part of https://github.com/theKashey/react-focus-on build on top of this library
>   
>   * that is the solution you are looking for

Thanks a lot for the fast answer! It was not a hard thing to implement myself, but I will consider using `react-focus-on`. Amazing job on all of your repos by the way 🚀
