### ISSUE TITLE
Can I add some selectors to whitelist?

### ISSUE THREAD

**Issue by naxxateux** [theKashey/react-focus-lock#26]
Hi!

Thanks for the amazing plugin. What I have here is not an issue but a short question actually. Let’s suppose that I have a customer support or helpdesk plugin or smth like that (Intercom, Livetex, etc.). Usually this type of plugins create separate modal dialogs. When I have my own modal dialog (wrapped with FocusLock) on the screen I can't focus on a third-party dialog.

So, the question is — can I add a selector (from third-party dialog) to a some kind of whitelist? Should I use `group` property for this?

Thanks in advance.

**Comment by naxxateux** [comment]
Answering my own question: I need to add `data-focus-lock="groupName"` to third-party container somehow.

**Comment by theKashey** [comment]
Yeah, that will work.
