### ISSUE TITLE
Returning focus to element inside an iframe

### ISSUE THREAD

**Issue by spatel49** [theKashey/react-focus-lock#296]
Hey there!

I hope you're doing well. I just wanted to inform you of an issue we're facing with unexpected focus behavior when upgrading our `react-focus-lock` package from `2.11.2` to `2.9.3`. 

The problem we’re seeing is that the iframe document unexpectedly scrolls to the top of the page after closing certain modals, because it tries to return focus to the iframe element, and then focuses the header element (the first focusable node in the document). Ideally, it should look through the iframe when it’s determining what the active element is when the focus lock is first set up.

**Comment by theKashey** [comment]
🤔 Correct, the current return focus logic is not "entering" iframes and/or shadow dom, so cannot properly return element where it belongs. That should not be affected by the version change as return focus always was operating within a single document.

Anyway, tell me how exactly one can reproduce the problem?
- there is a host page with focus-lock
- it renders an iframe
- the focus is within given iframe
- who opens the modal?
