### ISSUE TITLE
Running linter and tests on CI

### ISSUE THREAD

**Issue by ezhlobo** [theKashey/react-focus-lock#3]
BTW, what do you think about setting up CircleCI or Travis? They both should be free for open source projects.

It will make this repository more friendly for others and help you to avoid bad code in master.

I can push CircleCI config if you are ok with it. Or let me know what do you think about it.

**Comment by theKashey** [comment]
I never used CircleCI, but keen to try. I hope it will be better than Travis, which is a quite standard, but not a quite great.
PS: And don't forget about badges!
