### ISSUE TITLE
onDeactivation callback is called on render in StrictMode

### ISSUE THREAD

**Issue by Ke1sy** [theKashey/react-focus-lock#308]
I use the `React.StrictMode` in my application and `onDeactivation` callback for some logic.
I expect this callback to be called on unmounting or on disabling FocusLock, but in StrictMode it is called on render (it shouldn't happen), also I see that 'onActivation' also is called 2 times:
![image](https://github.com/theKashey/react-focus-lock/assets/26119263/dd3caeba-caf9-4473-b33f-5bdfed630d96)

In comparison to it I am attaching the correct behaviour for not StrictMode: 
![image](https://github.com/theKashey/react-focus-lock/assets/26119263/2da94dfc-2f58-4acc-b536-1afe44263096)

Sandbox: https://codesandbox.io/p/sandbox/react-focus-lock-demo-forked-nlsfpv
Steps to reproduce this issue:
1) open console
2) click the button
3) review the logs.

To see the expected behaviour, - just remove the `<StrictMode>` in App.js

It looks like this behaviour is broken when 'react-focus-lock' is used in the application with React v18.

**Comment by Ke1sy** [comment]
@theKashey Please, review. Thanks!

**Comment by theKashey** [comment]
👍 that's a valid confusion
- first activation callback is skipped because lock is not yet fully initialized (no ref assigned)
- then deactivation is called via StrictMode rerunning effects
- and then two activation callbacks called because there no prevention for double run
