### ISSUE TITLE
[Question] Controlling which element get focus

### ISSUE THREAD

**Issue by ryxle** [theKashey/react-focus-lock#31]
I have set of buttons in a custom modal popup. According to current implementation what happen is first button in the group get the focus. What I want to do is to set focus for the last item in the button group. How can I achieve this behavior? Sorry if this was documented in readme I didn't see that. @theKashey

**Comment by theKashey** [comment]
Yeah, it was documented - https://github.com/theKashey/react-focus-lock#autofocus
You can add data-attributes on HTML tags to control autofocus, or use exported React Components, to do, actually, the same.

```js
<button data-autofocus />

<div data-autofocus-inside><button/></div>

``
