### ISSUE TITLE
Failing to import ESM module in Node

### ISSUE THREAD

**Issue by brynshanahan** [theKashey/react-focus-lock#316]
A consumer of our component library is trying to import react-focus-lock in Vitest as a nested dependency which is failing because Node imports the ESM module as `{ default: FocusLockComponent }` rather than `FocusLockComponent`

I have a reproduction [here](https://github.com/brynshanahan/Vitejs-Vite-forked). If you run `yarn workspace common node-test` then it shows that the component is being imported incorrectly. 

I think a solution might be to use the `.mjs` extension for the dist/es2015 folder but I'm not totally sure

**Comment by brynshanahan** [comment]
The way I've gotten our modules to work in most environments is the following config in our package.json files. I'm not sure how necessary it all is but I've been trying to follow what the team at [React Spectrum](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/accordion/package.json) does with their modules

```json
{
    "main": "dist/cjs/index.cjs",
    "module": "dist/module/index.js", // same as "import" module but without the .mjs ext
    "types": "dist/types/index.d.ts",
    "exports": {
        "import": "./dist/esm/index.mjs",
        "require": "./dist/cjs/index.cjs",
        "types": "./dist/types/index.d.ts"
    },
}
```

**Comment by theKashey** [comment]
Focus Lock was already _migrated_ to ESM, but that caused a little incident.
Unfortunately, it's less about this particular library, it is esm compatible, but about all other libraries it depends on, the ones that has to be updated before this one can migrate.

On my short list of things
