### ISSUE TITLE
Option to allow clicks outside the focus trap

### ISSUE THREAD

**Issue by lazyd3v** [theKashey/react-focus-lock#317]
I'm wondering if it's possible to deactivate the focus trap and allow the click event to pass through. 

In other words, if I use the keyboard for navigation, I'll be "trapped". But if I click on some element outside the trap, the trap should be immediately deactivated and allow the click event to do its thing. 

At the moment, it's not the case, and here's the [example](https://codesandbox.io/p/sandbox/react-focus-lock-forked-9fw7rm?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyyo721500073b6nlmcuaycs%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyyo721400033b6nh24rpsnl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyyo721400043b6nf788a1g9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyyo721400063b6neo61h57z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyyo721400033b6nh24rpsnl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyyo721400023b6ngdzdarfk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clyyo721400033b6nh24rpsnl%2522%252C%2522activeTabId%2522%253A%2522clyyo721400023b6ngdzdarfk%2522%257D%252C%2522clyyo721400063b6neo61h57z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyyo721400053b6ngr0jno76%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyyo721400063b6neo61h57z%2522%252C%2522activeTabId%2522%253A%2522clyyo721400053b6ngr0jno76%2522%257D%252C%2522clyyo721400043b6nf788a1g9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyyo721400043b6nf788a1g9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). If you activate the trap, the input at the bottom of the page will not be clickable.

**Comment by theKashey** [comment]
It is accessible. Here - I've added `onClick` to disable trap and it is working.
https://codesandbox.io/p/sandbox/react-focus-lock-forked-9fw7rm?file=%2Findex.js%3A56%2C39

Elements outside the trap are clickable and focusable. Focus-Lock triggers right after and returning focus, so you cannot "sense" it.

If you want a little bit automated solution, then https://github.com/theKashey/react-focus-on exposes "clickoutside" as a part of it's API
