### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by TrevorRice** [theKashey/react-focus-lock#320]
Hi all!

With the [upcoming release of React 19](https://react.dev/blog/2024/04/25/react-19), are there any plans to update `react-focus-lock` to be React 19 compatible (once available)? I'm thinking specifically of the package's [`peerDependency` list](https://github.com/theKashey/react-focus-lock/blob/ad2756ca9d68691aac71c21d4135c6d27596483f/package.json#L67-L68) and its exported types.

Cheers!

**Comment by bdrtsky** [comment]
This shouldn't be closed. Please update package.
