### ISSUE TITLE
[Bug] missing type definisions 

### ISSUE THREAD

**Issue by felixmosh** [theKashey/react-focus-lock#325]
`v2.13.0` types field (in package.json file) is pointing to a missing file, which breaks TS.

**Comment by KieraDOG** [comment]
We’ve encountered the same issue in our project

**Comment by wangzhenlalala** [comment]
same here

**Comment by theKashey** [comment]
Sorry, that was an incorrect migration from ESM  (that went sideways - https://github.com/theKashey/react-focus-lock/issues/301)
Restored package.json, but not the files.

- 2.13.0 was deprecated
- 2.13.1 just released, please update
