### ISSUE TITLE
Keeping focus trapped in a single focus lock group when there are multiple focus locks present and whitelist is enabled

### ISSUE THREAD

**Issue by alex-e-leon** [theKashey/react-focus-lock#342]
Hey @theKashey - I'm not sure whether this is a request for advice, a missing feature or a bug.

In my scenario I have multiple focus traps present on the page - specifically in my case I have 2 dialogs open, one sitting on top of the other (And yes -  I don't like having nested dialogs either - but it is required).

Currently, focus lock allows you to focus to elements inside any of the focus locks present, which means that its possible to tab to the dialog that is behind the currently active dialog. I'd like to prevent this behaviour and have the focus locked only to the most recently created focus-locked container.

I had a look at the groups api/description, and it confused me, because the groups api seems to support the out of the box behaviour - but maybe I've misunderstood how groups are supposed to be used.

If you have any suggestions for how to implement this - please let me know!

Thanks.

**Comment by theKashey** [comment]
You are right - this is a built-in behaviour and only the top-most FocusLock can be active at a single point of time.

You may "control" this moment by:
- shards, so focus-lock will consider other elements as a part of it
- whiteList, so focus-lock will ignore some locations
- and that is all, there is no other way to get out of the Lock

Please share your code, there is something "not right" there.

**Comment by alex-e-leon** [comment]
It took me a little bit to strip back everything and find a minimal reproducible build, but now that I have it looks like the issue is caused by the `whiteList` prop.

As soon as you set a whitelist like in the following example, and add 2 "dialogs" onto the page, focus does not stay trapped within a single component.

```
import React from 'react';
import FocusLock from 'react-focus-lock';

function Dialog({children}: {children: React.ReactNode}) {
  return (
    <FocusLock whiteList={node => !!document.querySelector('.doesNotExist')?.contains(node)}>{children}</FocusLock>
  );
}

export default Dialog;

```

So yeah I guess we can officially call this a bug : )

**Comment by theKashey** [comment]
You've written this function, so that's a bug in your code.
Dont use `whiteList` without a very good reason and without a very straight logic. It's a very brute-force solution for problems that should never happen.

**Comment by alex-e-leon** [comment]
Sorry i should have been more clear in my previous report.

In my case I'm using whitelist to allow dialogs to work with one of those 3rd party product tour products that I have no control over (in my case its intercom) which iframes in its own dialogs on top of my app - and my actual selector looks like `whiteList={node => !!document.querySelector('[data-intercom-frame="true"]')?.contains(node)}` - As far as I'm aware whitelist is the best approach for solving this use case?

But I wanted to put together a simple test case, so I put together a test case without intercom on the page and a whitelist that selected nothing.

Whitelist seems to work fine when there is only a single FocusLock on the page, but the issue comes up when there are multiple FocusLocks.

**Comment by alex-e-leon** [comment]
Ah right, it looks like I skimmed over the docs for whitelist and assumed it worked a little differently - thats on me 😅. 

But now that I'm in the weeds and properly testing out whitelist - I'm not sure I fully understand how whitelist is supposed to work.

Let me know if this interpretation is correct: using white-list won't add focusable items that match into the focus order or in anyway change the behaviour of focus-trap with regards to focusable items outside of the whitelisted areas, it just prevents any fights with other focus managers that might be applied to those areas? Is that right?

Maybe a more detailed explanation in the whitelist docs addressing these questions might be helpful for others.

And as always thanks for your help @theKashey and for the great work you do.

**Comment by theKashey** [comment]
In very short FocusLock will do _something_ only if there is no active element at all or the current activeElement is "white listed" - https://github.com/theKashey/react-focus-lock/blob/master/src/Trap.js#L145

In all other cases focus lock will not do anything. whileList is more about "not working" rather than "working"

----

If you need something to "work", ie change focus order for example, consider using shards
```tsx
// ourside component, so ref is "stable"
const intercomRef = {
 get current() {
   // dynamically reference to the Intercom
   return document.querySelector('[data-intercom-frame="true"]');
}
}

//. ....
// inside component
<FocusLock shards={[intercomRef]}>...
```

**Comment by alex-e-leon** [comment]
Thanks @theKashey - I'm marking this as closed, because in the end it turned out to be user error after all. Maybe it could help if some of the above was added to the docs, but otherwise I call this case closed.

**Comment by theKashey** [comment]
Docs absolutely need an extra refimenent pass.
