### ISSUE TITLE
Support React 19

### ISSUE THREAD

**Issue by lcswillems** [theKashey/react-focus-lock#344]
Hey!

React 19 has been recently released. However, react-focus-lock doesn't seem to be compatible at the moment.

**Comment by theKashey** [comment]
Fixed in v2.13.3

**Comment by lcswillems** [comment]
Hey @theKashey I don't think it is resolved. "react-focus-lock" uses dependencies that require React 18 as peer-dependency.

One could say that it is the issue of the dependencies but "react-focus-lock" has decided to use them, and they are part of "react-focus-lock" code.

So I don't think the issue is resolved. Possible to reopen please? :pray:

**Comment by lcswillems** [comment]
Investigated and you should force react-clientside-effect to be at least 1.2.7.

On my side I upgraded react-focus-lock but it kept the same version of react-clientside-effect.
