### ISSUE TITLE
Imports are not permitted in module augmentations.

### ISSUE THREAD

**Issue by SergeyIsakhanyan** [theKashey/react-focus-lock#38]
Please see the attachment below. Getting this error when trying to build React app. Any ideas how to fix this?

Error message: imports are not permitted in module augmentations
[ts] Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.

![react-focus-lock](https://user-images.githubusercontent.com/34714457/44908218-e370c500-ad44-11e8-824a-7a281672068a.PNG)

**Comment by theKashey** [comment]
my bad. Those imports are being injected by Webstorm, and I always have to remove them.

**Comment by theKashey** [comment]
Fixed in 1.12.1. Thank you for the bug hunting! (and using TS 🧐)

**Comment by SergeyIsakhanyan** [comment]
Thank you for fast fixing.
