### ISSUE TITLE
Missing document check

### ISSUE THREAD

**Issue by valendres** [theKashey/react-focus-lock#39]
**Lock.js**
```
onActivation = () => {
    this.originalFocusedElement = this.originalFocusedElement || document.activeElement;
};
```

The existence of the document object is not tested in onActivation, this can cause Jest unit tests to fail. If setTimeout is not included in a unit test, this code is executed after Jest has already cleaned up the document object.

**Comment by theKashey** [comment]
v1.13.1 👍 

Jest/Document around problems emerges every quarter.
