### ISSUE TITLE
Focus Lock + PopperJS Issues

### ISSUE THREAD

**Issue by amcdnl** [theKashey/react-focus-lock#41]
## Issue Description
When combining PopperJS w/ Focus Lock there are various overflow issues.

## Steps to reproduce
- Set html, body to 100% height w/ overflow auto
- Create a popperjs element
- Link the popper element to something that is positioned at the bottom of a page.
- Inside the popper element, put a focus lock element

Thats quite a complex combination, I'll try to create a repo case. In the meantime, here is a video that might help. https://www.screencast.com/t/VIH2TlRNep

**Comment by theKashey** [comment]
You are about "page jump"? Try to add `autofocus={false}` to the Lock props - it will not autofocus element inside a Lock, and thus will not trigger page jump.
