### ISSUE TITLE
Wrong name of file in published package

### ISSUE THREAD

**Issue by ezhlobo** [theKashey/react-focus-lock#5]
It looks like we have the wrong name of 'AutoFocusInside' file. 

When I pulled the latest package I got this error:

>./node_modules/react-focus-lock/dist/index.js
>Module not found: `/Users/ezhlobo/Work/Datarockets/accubitz/accubitz-react/node_modules/react-focus-lock/dist/AutoFocusInside.js` does not match the corresponding path on disk `AutofocusInside.js`.

**Comment by theKashey** [comment]
My fault. I should wipe dist folder before the build.

**Comment by ezhlobo** [comment]
@theKashey what do you think about removing of `/dist` directory through `build` npm-script. Just before building.

**Comment by theKashey** [comment]
Yep, that's I have to do. And add linting are pre-commit hook :)
