### ISSUE TITLE
Disable focus programmatically

### ISSUE THREAD

**Issue by visualcookie** [theKashey/react-focus-lock#55]
Hi,

I'm trying to disable the focus on an element programmatically, by changing an option variable.

Current lineup:
``` jsx
<FocusLock disabled={disabledFocus}>
  <div
    tabIndex="1"
    role="dialog"
    aria-labelledby={heading}
    aria-describedby={subHeading}
    className={css(styles.modal)}
    style={{ ...modalStyles[state] }}
    state={state}
    onKeyDown={this.handleKeyClose}
  >
    ...
  </div>
</Focus>
```

I toggle this state in a subcomponent of my modal via redux. I've also checked the React devtools, and in fact, the disabled will be set to true/false regarding the current state of `disabledFocus` but somehow the focus is still on the `<div />`.

How can I disable the focus once another component inside of my modal opens?

**Comment by theKashey** [comment]
You are not disabling a focus, you are disabling a lock. Without `returnFocus` property it would do nothing, with `returnFocus` - focus the last focused element (including thing div, if it was it)

**Comment by visualcookie** [comment]
> You are not disabling a focus, you are disabling a lock. Without `returnFocus` property it would do nothing, with `returnFocus` - focus the last focused element (including thing div, if it was it)

What is the correct way of using `returnFocus`? Does this prop accept a function?

**Comment by theKashey** [comment]
That's a boolean prop. There are `onActivation` and `onDeactivation` props, which are functions.

**Comment by visualcookie** [comment]
Thanks, will check that out tomorrow. And get back to this issue, if I'm running into any problems.
