### ISSUE TITLE
Focus guards' inline-style conflicts with Content Security Policies

### ISSUE THREAD

**Issue by chandlerprall** [theKashey/react-focus-lock#56]
The focus guards created by [Lock.js](https://github.com/theKashey/react-focus-lock/blob/master/src/Lock.js#L107-L108) have their hidden style applied inline, this breaks most Content Security Policies (https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which prevent inline styes. Instead, the hidden styles should be applied by a CSS+classname _or_ on componentDidMount, access the guards by ref and set `theref.style.width = ...`, etc

**Comment by chandlerprall** [comment]
Nevermind! Since v15 React applies the style attributes through the JS DOM API, there's something else going on in the testing I did.

**Comment by theKashey** [comment]
Keep me up to date
