### ISSUE TITLE
focus lock and nvda browse mode.

### ISSUE THREAD

**Issue by manatde** [theKashey/react-focus-lock#60]
I am using focus lock on my modal. tabbing is working perfectly. continuous tabbing inside the modal working as a loop. This is good for me. But in browse mode of NVDA , inside the focus lock arrow keys are working but it is not looping. Could you please give some suggestion to fix this?

**Comment by manatde** [comment]
I am using focus lock on my modal. tabbing is working perfectly.  continuous tabbing inside the modal working as a loop. This is good for me. But in browse mode of NVDA , inside the focus lock arrow keys are working but it is not looping. Could you please give some suggestion to fix this?

**Comment by theKashey** [comment]
This is correct behavior - arrow keys are not changing "active", ie focused elements, thus you may escape the lock.
There is another library to complete this case - (aria-hidden)[https://github.com/theKashey/aria-hidden], which will hide the rest of a document from screen readers, and "fix" the problem that way. Not sure it would properly handle looping, but should do the job.

You may try it, replacing `react-focus-lock` with `react-focus-on` with scroll lock disabled
```js
import {FocusOn} from 'react-focus-on';

<FocusOn 
  scrollLock={false} // disable scroll lock, you might not need it
  noIsolation // disable click handler isolation, you might not need it
>
  your content
</FocusOn>
```
^ by default scroll lock is quite aggressive - locking focus, scroll, casting `aria-hidden` on the rest and appling `pointer-events:none` to all the hidden nodes.

**Comment by manatde** [comment]
Thanks a lot Kashey
