### ISSUE TITLE
Skips <video/>

### ISSUE THREAD

**Issue by catamphetamine** [theKashey/react-focus-lock#61]
I'm using this library for locking focus inside my custom slideshow component.
The slideshow can play videos.
What I noticed is that when hitting `Tab` key it doesn't tab to the `<video/>` element (always skips it), but it does tab to the `<video/>` element when hitting `Shift + Tab` (doesn't skip the video).

Also, I noticed that when I add `whiteList={node => { console.log(node); return false; }}` it stops working (lets the focus outside and doesn't trap it).

```js
<FocusLock
  returnFocus
  autoFocus={false}>
  ...
</FocusLock>
```

**Comment by theKashey** [comment]
1. I've added a story for video, and it working without any issues
2. `whiteLists` is about allowing focus lock to handle focus on some nodes. By returning false you are asking it to do _nothing_. Like a - please don't touch.

**Comment by catamphetamine** [comment]
Ok. I added `<video/>` to your demo and it works.
https://codesandbox.io/s/7k134pmp30
Maybe it's my application doing something differently then.
