### ISSUE TITLE
[v1.19.0] Focus jumps to the first element 

### ISSUE THREAD

**Issue by vrizo** [theKashey/react-focus-lock#63]
Hi, @theKashey !

Thanks for the great tool, we use it in our project for a long time.

I noticed an issue in v1.19.0: focus lock works perfectly, but if you change your browser tab to another one and then switch back, focus jumps to the first element of the locked group. The bug can be easily reproduced in Firefox 66, Chrome 73 and Safari 12.1 on Mac.

Here is an screencast:

<img src="https://media.amplifr.com/images/social_images/011/521/392/img.gif" alt="bug screencast" />

It might be useful to diagnose the issue: these buttons have an onClick event with `event.currentTarget.blur()` to prevent applying of focus styles after a click.

I have downgraded to 1.18.3, and it works as expected now.

Let me know if I can you with the problem.

Thanks!

**Comment by theKashey** [comment]
It detects that window loses focus and tries to handle focus on restore. Before it was restoring the last focused element, and not it _thinks_ that it should be the first element.

The problem - by some reason it thinks that focus is changed, ie `activeElement` is not inside a lock. As far as I could see - changing tabs do not change `activeElement`, so the reason why logic is triggered is unclear.

**Comment by theKashey** [comment]
Ok, so according to your video - focus __is__ on body, ie no real active element, and thats why it react that way.

**Comment by theKashey** [comment]
Try 1.19.1, should fix this sticky behaviour.

**Comment by vrizo** [comment]
@theKashey, thanks a lot for your quick response! 1.19.1 works amazingly! I think we can close this issue now.
