### ISSUE TITLE
Iframe inside FocusLock losing focus

### ISSUE THREAD

**Issue by vctormb** [theKashey/react-focus-lock#65]
I'm using the FocusLock to wrap a modal that contains React components and a React iframe component. The iframe is a text editor which contains a toolbar with a dropdown.

When I press `enter` to open the dropdown options the iframe loses focus and the first focusable element inside the modal is focused again.

Is there a way to not lose the iframe focus that already contains accessibility features?

**Comment by theKashey** [comment]
Iframes were supported from the begging, let me double check

**Comment by theKashey** [comment]
I've added an iframe-related story and it's working as expected. I could not reproduce the issue, and might not know the real reasons for the strange behavior you are talking about.

**Comment by vctormb** [comment]
I'll try to create an example to show you exactly.

**Comment by theKashey** [comment]
Feel free to reopen the issue if it's still valid.
