### ISSUE TITLE
Adding Guard with Portals so that Focus returns to first focusable element after last.

### ISSUE THREAD

**Issue by bradley** [theKashey/react-focus-lock#66]
Im using [react-portal](https://github.com/tajo/react-portal#readme) for placing a Modal component into the `body` of my HTML inside of a react app. On top of this I am using `react-focus-lock` in hopes that I can lock focus to the Modal while it is mounted, and have tabbing through focusable elements loop over them, returning to the first focusable modal element once the final focusable element has been tabbed from.

This is according to the [W3C modal accessibility spec](https://www.w3.org/TR/wai-aria-practices/#dialog_modal):

> If focus is on the last tabbable element inside the dialog, moves focus to the first tabbable element inside the dialog.

My code is structured as follows (simplified for example):

There is a `ModalContainer` that uses `react-focus-lock` to wrap the `Modal` in a focus lock, passing the Modal a ref to use on itself via the "Childred as Function" react pattern:

```javascript
import React from "react";
import FocusLock from "react-focus-lock";

class ModalContainer extends React.Component {
  constructor(props) {
    super(props);

    this.modalRef = React.createRef();
  }

  render() {
    const { children, render = children } = this.props;

    return (
      <FocusLock shards={[this.modalRef]}>
        {
          render({
            modalRef: this.modalRef
          })
        }
      </FocusLock>
    );
  }
}

export default ModalContainer;
```

The `Modal` component imports this `ModalContainer` so that it may wrap itself inside of it and obtain a reference to the `ref` `react-focus-lock` wants for its `shards` property:

```javascript
import React from "react";
import { Portal } from "react-portal";

import ModalContainer from "../containers/ModalContainer";
import Backdrop from "../views/Backdrop";
import ModalView from "../views/ModalView";

class Modal extends React.Component {
  render() {
    return (
      <ModalContainer>
        {
          ({
            modalRef
          }) => {

            return (
              <Portal>
                <Backdrop>
                  <ModalView ref={modalRef}>
                    <div><a href="http://google.com">first</a></div>
                    <div><a href="http://google.com">second</a></div>
                  </ModalView>
                </Backdrop>
              </Portal>
            );
          }
        }
      </ModalContainer>
    );
  }
}

export default Modal;
```

This all works to lock focus to the Modal and not to other focusable elements on the page, as expected. _However_, once the final focusable element (the link with text "second") is tabbed away from, focus moves on to the tabs in my browser window. I can "backwards tab" back to the modal, but what I want is to _keep_ tabbing within the modal.

As per `react-focus-lock`'s documentation, "guards" may be added to arrive at this desired goal:

> As you may know - FocusLock is adding Focus Guards before and after lock to remove some side effects, like page scrolling. But shards will not have such guards, and it might be not so cool to use them - for example if no tabbable would be defined after shard - you will tab to the browser chrome.

> You may wrap shard with InFocusGuard or just drop InFocusGuard here and there - that would solve the problem.

However, I have been unable to figure out how to actually do this. Ive placed `InFocusGuard` components in several parts of my modal setup without any noticeable results.

If `InFocusGuard` works as described, can you tell me where to place `InFocusGuard` in my setup?

**Comment by theKashey** [comment]
You did it a bit complex. Here is two examples, which would "just work"
```js
class Modal extends React.Component {
  render() {
    return (
      <ModalContainer>
        {
          ({
            modalRef
          }) => {

            return (
              <Portal>
                <Backdrop>
                  <InFocusGuard> // place focus guards around Modal
                    <ModalView ref={modalRef}>
                      <div><a href="http://google.com">first</a></div>
                      <div><a href="http://google.com">second</a></div>          
                    </ModalView>
                  </InFocusGuard>
                </Backdrop>
              </Portal>
            );
          }
        }
      </ModalContainer>
    );
  }
}
```

The `second` example would be absolutely the same - just replace `FocusGuard` with a `FocusLock`.

**Comment by bradley** [comment]
Ok thanks. The `InFocusGuard` example didnt work for me (tabbing still continued to the browser UI), but replacing `InFocusGuard` with the base `FocusLock` seems to work. Ill need to readdress my structure but this gets me going. Cheers.
