### ISSUE TITLE
PersistentFocus + FreeFocusInside

### ISSUE THREAD

**Issue by czana** [theKashey/react-focus-lock#71]
Hi! I have to use `PersistentFocus` on my search input to provide constant focus, but when I combine it with `material-ui` components I get `focus-fighting` log error which I tried to remove (without success) by wrapping those elements with `FreeFocusInside` tag. When I remove `PersistentFocus` logs do not appear but I do not have my functionality. Is it a correct behaviour or am I doing something wrong?

Here I prepared minimal example to show you my case:
https://codesandbox.io/s/wizardly-sutherland-lv1jj
PS. In order to modify that code on sandbox you need to remove input through browser inspector as `react-focus-lock` steals focus from codesandbox ;)

**Comment by theKashey** [comment]
In short - FreeFocusInside is not working, as long as `container` prop has no effect.
The menu is shown using standard MUI tools and _focusable_ div is not accessible for you. The only way (without ever worse hacks) is to use `whiteList` prop, while would completely __hide__ menu modal from a focus lock.
```js
<div>
    <FocusLock 
        persistentFocus={true} 
        // allow focus on MUI
        whiteList={el => el && !el.classList.contains('MuiPaper-root')}
    >
        <input type="search" />
    </FocusLock>
```
But better just move menu inside the lock, as long as right now it's only mouse accessible. Creating lock for a single element might be a very bad idea.

**Comment by czana** [comment]
@theKashey thank you for explanation and for creating that library! Now I know how to handle that :)
