### ISSUE TITLE
v2.0.0 throws error on codesandbox

### ISSUE THREAD

**Issue by sandgraham** [theKashey/react-focus-lock#72]
Hi there, on the latest version, `v2.0.0`, there seems to be an issue compiling on codesandbox. I've make a sandbox [here](https://codesandbox.io/s/react-focus-lock-v200-module-problem-ifl4o) to reproduce it.
```
ModuleNotFoundError: Could not find module in path: 'focus-lock/constants' relative to '/node_modules/react-focus-lock/dist/cjs/Lock.js'
```
I don't get this with any version prior to `v2.0.0`.

I'll take a look and see if I can find any recent updates in that area but might need some help resolving.

Thanks!

**Comment by theKashey** [comment]
Working for me. Look like, but a sole reason, focus-lock is used in the older version.
Could you try to update codesandbox - might be sole important update was not landed.

**Comment by theKashey** [comment]
Just checked with a clear install of Firefox - everything is working.

**Comment by sandgraham** [comment]
I'm not sure why this wasn't working for me last night but it works fine now. I created a few sandboxes and the problem persisted across all of them but maybe I had something cached locally.

I just tested v2 in Chrome/Firefox/Safari and 👍. Thanks for your fast response!

**Comment by theKashey** [comment]
👍
