### ISSUE TITLE
Clickable elements below the fold in Safari

### ISSUE THREAD

**Issue by colebemis** [theKashey/react-focus-lock#79]
## Problem

In macOS Safari, clicking links below the fold inside the `FocusLock` component causes focus to jump to the first link instead of going the destination of the link.

![](https://user-images.githubusercontent.com/4608155/63062327-510df680-bead-11e9-946a-0f2196dc76c8.gif)

Here's a codesandbox that reproduces the issue: https://codesandbox.io/s/responsive-navigation-safari-bug-6hvj4

## Notes

* Removing the [`FocusLock`](https://github.com/theKashey/react-focus-lock#readme) component from the [`Drawer`](https://github.com/primer/doctocat/blob/master/theme/src/components/drawer.js#L54) component fixes this issue.
* Removing `tabIndex="-1"` from the wrapper div created by @reach/router also fixes this issue:

  ![image](https://user-images.githubusercontent.com/4608155/63305591-50ee6c00-c29c-11e9-840b-ef492f8731d7.png)

Related to https://github.com/primer/doctocat/issues/56

**Comment by theKashey** [comment]
`focus-lock` has the following logic - if the "distance" between last focused component and the current one is "more" than 1 - [move focus back to the last](https://github.com/theKashey/focus-lock/blob/master/src/focusMerge.js#L50).

And exactly this moment is not working. Let's try to find out why

**Comment by theKashey** [comment]
It seems to me - this is a pure Safari issue - https://codesandbox.io/s/responsive-navigation-safari-bug-jjf1m - clicking on the button does not select it, it focuses on the parent div.

**Comment by theKashey** [comment]
https://codesandbox.io/s/responsive-navigation-safari-bug-jjf1m - for now the only way to fix Safari behaviour is to apply focus by yourself
```js
document.addEventListener(
  "click",
  event => {
    console.log("click", event.target);
    event.target.focus();
    // event.stopPropagation();
  },
  true
);
```

**Comment by theKashey** [comment]
Ok, here is documentation - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

### Does clicking on a <button> give it focus?
No (even with a tabindex)

### Does tapping on a <button> give it focus?
No (even with a tabindex)

---

So the only ways to fix the problem (for now) are:
- don't use `tabIndex` on the parent, so it would not be focused, and focus would not be activated.
- whitelist parental focus, ie allow it
- using event handlers `focus` buttons and links munually, however it does not working really well, and breaking default browser behavior.

So - look like the only valid way, but still not quite cool, is `.2` - https://codesandbox.io/s/responsive-navigation-safari-bug-wnwv3
the problem - no "focus guards" around that parent, so you might "tabout" it, thus escape the lock.

**Comment by colebemis** [comment]
@theKashey Thank you so much for the quick response! Approach #2 seems like the most reasonable solution. I'll give it a shot 😄

**Comment by theKashey** [comment]
You know - try to combine .2 with that "click-focus" hack I've posted above. You still need to focus the element somehow, or background element will retain the focus.

**Comment by grsmvg** [comment]
I had the same issue and solved it this way (found this solution by someone else):

```
const focusLockWhiteList = el => !(el.getAttribute('role') === 'dialog' && el.tabIndex === -1);

<FocusLock whiteList={focusLockWhiteList}>
```

**Comment by theKashey** [comment]
I am not sure it's the right solution for a problem.

Actually, I am thinking about a better approach:
```js
// help browser to focus element you just clicked
document.addEventListener(
  "focus",
  event => {
    if(eventTargetContainsFocusLock) { 
      event.preventDefault(); // don't let focus to be set "trought" focus lock.
    }
  },
  true,
);
```

In the same time - there is already such logic - https://github.com/theKashey/react-focus-lock/blob/master/src/Trap.js#L121-L159

The problem:
## without whitelist
- the original event would be `prevented`, but focused element would be changed (this issue)

## with white list
- the original event would pass thought, focus lock will ignore focus change (that's not a solution)

## what shall be done
- the original even should be suspended.

## where? Or what is causing the initial issue
- `focus-lock` is enumerating all focusables and act depending on their relative positions.
- the distance between last element and the new is too "far", thus focus lock is activating the first element
- 😎focus lock shall threat "parents" in a different way. If the focus is received at parent - we shall bring it back to the last focusable element.

So - the real problem is assumtion that the "focus order" does not include your own parent. And it does not almost in all cases, except `reach-router`.

I think this is what shall be changed.

**Comment by theKashey** [comment]
Ok ^^^ that did not work. I could not preserve "focused elements" as long as they are not focusable in Safari. __But I've found a solution__.

>> https://codesandbox.io/s/responsive-navigation-safari-bug-kblg2

```js
 <div
// remove mouse down propagation from the lock
  onMouseDown={e => e.preventDefault()}
// restore just lost "default" behaviour
  onClick={e => e.target.focus()}
>
  <FocusLock>
    ....
```

I would gently ask you to test this solution:
- wrap with `onMouseDown` suspender
- compensate _suspension_ with onClick handler

**Comment by theKashey** [comment]
Please double check - running the provided example in Chrome and Safari - everything works as it should.

**Comment by theKashey** [comment]
Let's keep it open unless it's properly documented, or even implemented on the focus lock side.

**Comment by theKashey** [comment]
https://zellwk.com/blog/inconsistent-button-behavior/

Proposed in that article fix is the same I've tried before
```js
document.addEventListener('click', event => {
  if (event.target.matches('button') {
    event.target.focus()
  }
})
```

In other words - we __could__ recomend using this _hack_ more widely.

**Comment by SMccarrick** [comment]
I've come across an issue regarding this fix

> ```js
>  <div
> // remove mouse down propagation from the lock
>   onMouseDown={e => e.preventDefault()}
> // restore just lost "default" behaviour
>   onClick={e => e.target.focus()}
> >
>   <FocusLock>
>     ....
> ```

So I added this fix to the parent div but the issue I was having was that `e.preventDefault()` was bubbling down to native form elements and causing them to not perform there default actions such as a select field showing its options onClick.

I tried to implement this fix but no dice

> ```js
>  <div
> // remove mouse down propagation from the lock
>   onMouseDown={e => e.preventDefault()}
> // restore just lost "default" behaviour
>   onClick={e => {
>     if (e.target !== e.currentTarget){
>       return
>     }
>     e.target.focus()
>  }}
> >
>   <FocusLock>
>     ....
> ```

**Comment by theKashey** [comment]
The only "working" solution, as described above
- list `target div` in `shards`, ie allow it to be focused
- or use `white list` to "hide" it
- or use `className` to "hide" it
- or "prevent default", which breaks more than it fixes.

No _real_ solution today  :(

Except for the way adopted by [reakit](https://reakit.io) - DON'T USE "BUTTONS" - see https://twitter.com/diegohaz/status/1176998100495491072

**Comment by spqsh** [comment]
Hey folks!
A bit late to the party, but we managed to fix it by adding `tabIndex={0}` to links inside `FocusLock`: https://codesandbox.io/p/sandbox/responsive-navigation-safari-bug-forked-3nlggp
