### ISSUE TITLE
It has warning about mandatory "key" property

### ISSUE THREAD

**Issue by ezhlobo** [theKashey/react-focus-lock#8]
It shows a warning in the console that "key" is important for each item in arrays. And it refers to Lock.js file.

PS. What do you think about using jest? Jest has everything that we have right now out of the box (except integration with enzyme). And it catches

**Comment by theKashey** [comment]
I am not a Jest-lover – it is too all-in-one for me, but sometimes it is useful. It is far easier just to provide a better scaffolding. Sometimes I am thinking about `create-react-testing-app` - with zero configuration like Jest, but on mocha 👽 .

**Comment by ezhlobo** [comment]
@theKashey it's no more the case starting from version 1.5.3. Thank you, I close the issue!
