### ISSUE TITLE
Manually provide Ref

### ISSUE THREAD

**Issue by klimashkin** [theKashey/react-focus-lock#85]
Hi! I'm trying to to use `react-focus-lock` with [re-resizable](https://github.com/bokuweb/re-resizable) and produce only one final div.
But `re-resizable` doesn't have ref forwarding, but provides `resizable` prop in its own instance that points to the final div.

I was trying to take this div, put into own artificial `this.ref` object and feed it to `shards`, like that:
```jsx
<FocusLock className={modalClass} autoFocus={autoFocus}
           as={Resizable} shards={[this.ref]}
           lockProps={{
             minWidth: 400,
             minHeight: 200,
             ref: i => this.ref.current = i.resizable,
             defaultSize: {width: 'auto', height: 'auto'},
           }}>
    {children}
</FocusLock>
```

But it seems to be not working. Is there any other approach that might help?

**Comment by klimashkin** [comment]
It seems to be working this way!
```jsx
const ResizableWithRef = forwardRef((props, ref) =>
  <Resizable {...props} ref={i => i && ref(i.resizable)}/>
);

<FocusLock className={modalClass} autoFocus={autoFocus}
           as={ResizableWithRef} 
           lockProps={{
             minWidth: 400,
             minHeight: 200,
             defaultSize: {width: 'auto', height: 'auto'},
           }}>
  {children}
</FocusLock>
```

But I wish there were another one to avoid extra wrappers, like manually passing dom element to to FocusLock

**Comment by theKashey** [comment]
Like ‘useFocusLock’ hook.

**Comment by theKashey** [comment]
Hey! Look like the next version is going to break this fix - `ref` would become `RefObject`, not callback.

**Comment by klimashkin** [comment]
You mean next version of re-resizable of focus-lock?

**Comment by theKashey** [comment]
of focus-lock. But I would provide a helper function to handle `ref` regardless of its implementation.

**Comment by theKashey** [comment]
@klimashkin - your case got documented as a use case for `use-callback-ref`
https://github.com/theKashey/use-callback-ref#usetransformref-to-replace-reactuseimperativehandle

```js
import {useTransformRef} from 'use-callback-ref';

const ResizableWithRef = forwardRef((props, ref) =>
  <Resizable {...props} ref={useTransformRef(ref, i => i ? i.resizable : null)}/>
);
```

I am moving forward with #88, please update your transformer function as long as `ref` is no longer a function.

**Comment by klimashkin** [comment]
Since there is a workaround probably that is ok to close this issue
