### ISSUE TITLE
FocusLock children prop

### ISSUE THREAD

**Issue by nklhtv** [theKashey/react-focus-lock#86]
Does  [children prop](https://github.com/theKashey/react-focus-lock/blob/master/src/Lock.js#L150) of FocusLock required to be a single node or even a single dom node?
Does the `as` prop expected to forward a ref to a dom node?
I want to use the FocusLock like that:
```javascript
const MyComponent = React.forwardRef((props, ref) => {
    return <div ref={ref} {...props} />
});
...
<FocusLock as={MyComponent} className={'class-name'} lockPorps={{...}} />
...
```

**Comment by theKashey** [comment]
> Does the as prop expected to forward a ref to a dom node?

To some dom node around content, yes. No matter which one.

> Does children prop of FocusLock required...

It's required to be "anything renderable as children", which is usually just `node`.

**Comment by NikolaBorislavovHristov** [comment]
i cant find the case where you need children. that propType should not be required, because of the use case i described above.

**Comment by theKashey** [comment]
From #87

- [ ] move Sidecar out of Container
- [ ] remove restrictions from PropTypes
- [ ] for TS - infer the right children type
