### ISSUE TITLE
Focus going outside on swap in mobile browser.

### ISSUE THREAD

**Issue by shivwork** [theKashey/react-focus-lock#89]
Focus going outside on swap (On accessibility on mode ) in mobile web. 
Browser - Safari , chrome
Device - Mobile (iPhone 6)

**Comment by theKashey** [comment]
Could you provide more detailed instructions to reproduce the problem? What does mean "swap" here?

**Comment by shivwork** [comment]
This is my code -
<FocusLock>
      <OverlayModalView
        ModalContent={ModalContent}
        component={component}
        variation={variation}
        color={color}
        openState={openState}
        closeOverlay={closeOverlay}
        componentProps={componentProps}
        plccUser={plccUser}
        isLoggedIn={isLoggedIn}
        showCondensedHeader={showCondensedHeader}
      />
    </FocusLock>

Its (Focus lock) working fine in desktop. But in Mobile browser in accessibility on mode, When i Swipe forward or Swipe backward focus goes out of the Modal and its reads the back screen page contents.

**Comment by theKashey** [comment]
Ok. So __this is not a bug__. Focus lock could not contain `voice over` - as long as it's not focus based.
You need another library - [react-focus-on](https://github.com/theKashey/react-focus-on), which would _hide_ everything except the modal from screen readers using [aria-hidden](https://github.com/theKashey/aria-hidden).
