### ISSUE TITLE
No initial focus

### ISSUE THREAD

**Issue by EldRoos** [theKashey/react-focus-lock#92]
How do I use focus lock and having no input focused from start?

**Comment by theKashey** [comment]
set `autoFocus` prop to `false`. It will suppress any active focus outside the lock, but not move it inside.

**Comment by EldRoos** [comment]
I tried that, and still the first input within FocusLock element get focused.

**Comment by theKashey** [comment]
Check `persistentFocus`(default false) prop then - it will enforce _something_ to be focused in any case.
