### ISSUE TITLE
text selection in modal broken since google chrome 80

### ISSUE THREAD

**Issue by DonBras** [theKashey/react-focus-lock#94]
Since version update 80 of chrome (chrome edge as well) the text selection is broken in a modal dialog when a focusable element is present. FYI it still works well in latest ie11 and Firefox though.

```javascript
//"react": "16.12.0"
//"react-bootstrap": "0.33.0"
//"react-focus-lock": "2.2.1"

import React from 'react'
import { Modal } from 'react-bootstrap'
import FocusLock from 'react-focus-lock'

const ModalWrapper = props => {
  return (
    <Modal show={true}>
      <FocusLock persistentFocus={false}>
        <div>
          <div>FOO</div>
          <button>close</button>
        </div>
      </FocusLock>
    </Modal>
  )
}
```

**Comment by theKashey** [comment]
Please define "broken"

**Comment by theKashey** [comment]
Trying the default demo - https://codesandbox.io/s/react-focus-lock-48opn, and  it works. Probably somehow related to the `Modal` and your use case.

**Comment by DonBras** [comment]
Broken in terms of the text "FOO" in my example can not be selected, but it works in ie11 and firefox and it used to work in chrome 79 as well. The use case is having a modal with locked focus inside the modal. I opened that issue because i thought some other people use the Modal component from 'react-bootstrap' too and since it worked great in the past and either your or the bootstrap package changed in a while, there must be an issue with the new chrome version.

i made a small example
[https://codesandbox.io/s/react-focus-lock-c0rrv](url)

**Comment by theKashey** [comment]
So, this is not focus-lock related bug, and I am not sure why it works in other browsers/browser versions.

- The `Modal` has a `tabindex=-1`, which makes it focusable, but not tabbable (which is absolutely correct). Once you are trying to "select a text" - you do click on a `Modal`, and thus focusing it.
- The `Modal` is outside of the `FocusLock`
- And the focus returned back.

"Selection" works only if focus is on the body, ie nothing else is "selectable" between "you" and the body.

### How to fix
Put `FocusLock` outside of the `Modal`, or provide a `ref` to a `Modal` in `shards` prop (I've tried, look like `Modal` do not support `ref`)

**Comment by DonBras** [comment]
Thanks for the conclusion. I will try this out.
