### ISSUE TITLE
Any way to navigate from one focus-lock group to another?

### ISSUE THREAD

**Issue by LukasDeco** [theKashey/react-focus-lock#97]
In my app I have a sidebar with various links, and then a page with content. For each link, I have added a FocusLock with a `group="pageName1"`. Then inside that page, I also wrap some of the content in `group="pageName1"`. That way, the user can tab into the page contents from the link. My problem, is that I want to have a away to navigate outside of FocusLock with `group="pageName1"` into another page's focus group with FocusLock `group="pageName2"` using the keyboard. Is there a way to accomplish this? And order the focus lock groups in a certain order? Thanks!

**Comment by theKashey** [comment]
So there are two ways to "extend" `FocusLock` to other nodes - groups(html attributes) and shards(refs to nodes). Then you can _tab_ through all the nodes inside.

Once you reached the end of one group - it will go to another.

There is a way to let you jump to another FocusLock, not in the group using `whiteList` prop, but __not__ via sequential keyboard navigation.

Could you describe your use case in more details?

**Comment by LukasDeco** [comment]
So I am using groups, but I noticed that the FocusLock will stay within the elements inside the group and won't leave.

The whitelist prop allows you to escape the FocusLock group? How is that implemented?

So let's say, hypothetically, you have a set of links, Pizza, Hotdogs, and Ice Cream. When you click on one, you see all the images for that food. I want to be able to start at the Pizza link, and then tab all through the pizza images, and then after the last pizza image, tab to hotdogs, and I would be back inside the links and I could go around until I hit pizza again, and I would then start going through all the images again, 

Additionally, I would like to have the same set up when I start tabbing through pictures of hotdogs, etc. 

Ideally, there would be some way to move focus to the next link without having to tab through all that pages content. This action would be performed with some sort of alternative to tab.

Does that give enough info? And thank you for your quick response!

**Comment by theKashey** [comment]
Oh. That would be not easy to do, and this is not about FocusLock.
- focus lock is just a `guard`, not letting you focus something you should not. I would recommend to use `shards` prop to point to all "allowed" nodes, where you can dynamically add or remove your food popups
- the rest is more about "tab management", including `roving focus`, focus traps(ie do something on element focus, for example move focus to pizzas), keyboard navigation (ie arrows to navigate in "2d" world), which you have to implement by your own.
- in the same time dont forget about a11y, probably you will have to play with `aria-hidden` a bit

So, yeah, it would be a long journey, and it is about "tabs", not "focus". Check https://reacttraining.com/reach-ui/tabs/

**Comment by LukasDeco** [comment]
Thank you so much for your insights! So it sounds like possibly through some combination of using `shards` and my own implementation of keyboard navigation this could be accomplished? I'll look at Reach UI and see how their tabs get implemented. Thanks again!
