### ISSUE TITLE
Tabbing past last locked item focuses on data-focus-guard

### ISSUE THREAD

**Issue by dpouliot** [theKashey/react-focus-lock#99]
I'll try to be as brief as possible:
Repo A has a `Modal` component that uses `react-focus-lock`, which works (I'm not using any props).
Repo B has a `TabbedModal` component that imports `Modal`, which also works.
Repo B has a third component that imports `TabbedModal`. `TabbedModal` in the context of this third component fails in the following way: upon tabbing past the last element, focus shifts to `data-focus-guard` and fails to loop back to the first element. 
![image](https://user-images.githubusercontent.com/2699333/76862614-bf94a780-6834-11ea-86af-9f16ed9a805d.png)

**Comment by theKashey** [comment]
I cannot do anything without an example, and from your description is sounds like a very non standard situation.

**Comment by dpouliot** [comment]
I've got this working, so closing the issue.
